package database

import (
	"log"
	"starwars-api/models"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

var DB *gorm.DB

// Initialize sets up the database connection and runs migrations
func Initialize() {
	var err error

	// Connect to SQLite database
	DB, err = gorm.Open(sqlite.Open("starwars.db"), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Info),
	})
	if err != nil {
		log.Fatal("Failed to connect to database:", err)
	}

	// Auto-migrate the schema
	err = DB.AutoMigrate(
		&models.Character{},
		&models.Film{},
		&models.Species{},
		&models.Starship{},
		&models.Vehicle{},
		&models.Planet{},
		&models.Organization{},
		&models.Weapon{},
		&models.Event{},
	)
	if err != nil {
		log.Fatal("Failed to migrate database:", err)
	}

	log.Println("Database connected and migrated successfully")

	// Seed data if tables are empty
	seedData()
}

// seedData populates the database with initial Star Wars data
func seedData() {
	var count int64
	DB.Model(&models.Character{}).Count(&count)

	if count > 0 {
		log.Println("Database already contains data, skipping seed")
		// Але завжди перевіряємо та додаємо питання для вікторини
		SeedQuizQuestions()
		return
	}

	log.Println("Seeding database with Star Wars data...")

	// Create films first - all 9 main saga films
	films := []models.Film{
		{
			URL:          "https://swapi.dev/api/films/1/",
			Title:        "The Phantom Menace",
			EpisodeID:    1,
			OpeningCrawl: "Turmoil has engulfed the Galactic Republic. The taxation of trade routes to outlying star systems is in dispute.",
			Director:     "George Lucas",
			Producer:     "Rick McCallum",
			ReleaseDate:  "1999-05-19",
		},
		{
			URL:          "https://swapi.dev/api/films/2/",
			Title:        "Attack of the Clones",
			EpisodeID:    2,
			OpeningCrawl: "There is unrest in the Galactic Senate. Several thousand solar systems have declared their intentions to leave the Republic.",
			Director:     "George Lucas",
			Producer:     "Rick McCallum",
			ReleaseDate:  "2002-05-16",
		},
		{
			URL:          "https://swapi.dev/api/films/3/",
			Title:        "Revenge of the Sith",
			EpisodeID:    3,
			OpeningCrawl: "War! The Republic is crumbling under attacks by the ruthless Sith Lord, Count Dooku.",
			Director:     "George Lucas",
			Producer:     "Rick McCallum",
			ReleaseDate:  "2005-05-19",
		},
		{
			URL:          "https://swapi.dev/api/films/4/",
			Title:        "A New Hope",
			EpisodeID:    4,
			OpeningCrawl: "It is a period of civil war.\r\nRebel spaceships, striking\r\nfrom a hidden base, have won\r\ntheir first victory against\r\nthe evil Galactic Empire.",
			Director:     "George Lucas",
			Producer:     "Gary Kurtz, Rick McCallum",
			ReleaseDate:  "1977-05-25",
		},
		{
			URL:          "https://swapi.dev/api/films/5/",
			Title:        "The Empire Strikes Back",
			EpisodeID:    5,
			OpeningCrawl: "It is a dark time for the\r\nRebellion. Although the Death\r\nStar has been destroyed,\r\nImperial troops have driven the\r\nRebel forces from their hidden\r\nbase and pursued them across\r\nthe galaxy.",
			Director:     "Irvin Kershner",
			Producer:     "Gary Kurtz, Rick McCallum",
			ReleaseDate:  "1980-05-17",
		},
		{
			URL:          "https://swapi.dev/api/films/6/",
			Title:        "Return of the Jedi",
			EpisodeID:    6,
			OpeningCrawl: "Luke Skywalker has returned to\r\nhis home planet of Tatooine in\r\nan attempt to rescue his\r\nfriend Han Solo from the\r\nclutches of the vile gangster\r\nJabba the Hutt.",
			Director:     "Richard Marquand",
			Producer:     "Howard G. Kazanjian, George Lucas, Rick McCallum",
			ReleaseDate:  "1983-05-25",
		},
		{
			URL:          "https://swapi.dev/api/films/7/",
			Title:        "The Force Awakens",
			EpisodeID:    7,
			OpeningCrawl: "Luke Skywalker has vanished. In his absence, the sinister FIRST ORDER has risen from the ashes of the Empire.",
			Director:     "J.J. Abrams",
			Producer:     "Kathleen Kennedy, J.J. Abrams, Bryan Burk",
			ReleaseDate:  "2015-12-18",
		},
		{
			URL:          "https://swapi.dev/api/films/8/",
			Title:        "The Last Jedi",
			EpisodeID:    8,
			OpeningCrawl: "The FIRST ORDER reigns. Having decimated the peaceful Republic, Supreme Leader Snoke now deploys the merciless legions.",
			Director:     "Rian Johnson",
			Producer:     "Kathleen Kennedy, Ram Bergman",
			ReleaseDate:  "2017-12-15",
		},
		{
			URL:          "https://swapi.dev/api/films/9/",
			Title:        "The Rise of Skywalker",
			EpisodeID:    9,
			OpeningCrawl: "The dead speak! The galaxy has heard a mysterious broadcast, a threat of REVENGE in the sinister voice of the late EMPEROR PALPATINE.",
			Director:     "J.J. Abrams",
			Producer:     "Kathleen Kennedy, J.J. Abrams, Michelle Rejwan",
			ReleaseDate:  "2019-12-20",
		},
	}

	for _, film := range films {
		DB.Create(&film)
	}

	// Create species - expanded list
	species := []models.Species{
		{
			URL:             "https://swapi.dev/api/species/1/",
			Name:            "Human",
			Classification:  "mammal",
			Designation:     "sentient",
			AverageHeight:   "180",
			AverageLifespan: "120",
			SkinColors:      "caucasian, black, asian, hispanic",
			HairColors:      "blonde, brown, black, red",
			EyeColors:       "brown, blue, green, hazel, grey, amber",
			Language:        "Galactic Basic",
			HomeworldURL:    "https://swapi.dev/api/planets/9/",
		},
		{
			URL:             "https://swapi.dev/api/species/2/",
			Name:            "Droid",
			Classification:  "artificial",
			Designation:     "sentient",
			AverageHeight:   "n/a",
			AverageLifespan: "indefinite",
			SkinColors:      "n/a",
			HairColors:      "n/a",
			EyeColors:       "n/a",
			Language:        "n/a",
			HomeworldURL:    "",
		},
		{
			URL:             "https://swapi.dev/api/species/3/",
			Name:            "Wookiee",
			Classification:  "mammal",
			Designation:     "sentient",
			AverageHeight:   "210",
			AverageLifespan: "400",
			SkinColors:      "gray",
			HairColors:      "brown, black",
			EyeColors:       "blue, green, yellow, brown, golden, red",
			Language:        "Shyriiwook",
			HomeworldURL:    "https://swapi.dev/api/planets/14/",
		},
		{
			URL:             "https://swapi.dev/api/species/4/",
			Name:            "Rodian",
			Classification:  "sentient reptilian",
			Designation:     "sentient",
			AverageHeight:   "170",
			AverageLifespan: "unknown",
			SkinColors:      "green, blue",
			HairColors:      "n/a",
			EyeColors:       "black",
			Language:        "Galactic Basic",
			HomeworldURL:    "https://swapi.dev/api/planets/23/",
		},
		{
			URL:             "https://swapi.dev/api/species/5/",
			Name:            "Hutt",
			Classification:  "gastropod",
			Designation:     "sentient",
			AverageHeight:   "300",
			AverageLifespan: "1000",
			SkinColors:      "green, brown, tan",
			HairColors:      "n/a",
			EyeColors:       "yellow, red",
			Language:        "Huttese",
			HomeworldURL:    "https://swapi.dev/api/planets/24/",
		},
		{
			URL:             "https://swapi.dev/api/species/6/",
			Name:            "Yoda's species",
			Classification:  "mammal",
			Designation:     "sentient",
			AverageHeight:   "66",
			AverageLifespan: "900",
			SkinColors:      "green, yellow",
			HairColors:      "brown, white",
			EyeColors:       "brown, green, yellow",
			Language:        "Galactic Basic",
			HomeworldURL:    "",
		},
		{
			URL:             "https://swapi.dev/api/species/7/",
			Name:            "Twi'lek",
			Classification:  "mammals",
			Designation:     "sentient",
			AverageHeight:   "200",
			AverageLifespan: "75",
			SkinColors:      "orange, yellow, blue, green, pink, purple, tan",
			HairColors:      "none",
			EyeColors:       "brown, blue, hazel, green, dark",
			Language:        "Twi'leki",
			HomeworldURL:    "https://swapi.dev/api/planets/37/",
		},
		{
			URL:             "https://swapi.dev/api/species/8/",
			Name:            "Ewok",
			Classification:  "mammal",
			Designation:     "sentient",
			AverageHeight:   "100",
			AverageLifespan: "unknown",
			SkinColors:      "brown",
			HairColors:      "white, brown, black",
			EyeColors:       "orange, brown",
			Language:        "Ewokese",
			HomeworldURL:    "https://swapi.dev/api/planets/7/",
		},
		{
			URL:             "https://swapi.dev/api/species/9/",
			Name:            "Sullustan",
			Classification:  "mammal",
			Designation:     "sentient",
			AverageHeight:   "180",
			AverageLifespan: "unknown",
			SkinColors:      "pale",
			HairColors:      "none",
			EyeColors:       "black",
			Language:        "Sullustese",
			HomeworldURL:    "https://swapi.dev/api/planets/33/",
		},
		{
			URL:             "https://swapi.dev/api/species/10/",
			Name:            "Neimodian",
			Classification:  "unknown",
			Designation:     "sentient",
			AverageHeight:   "180",
			AverageLifespan: "unknown",
			SkinColors:      "grey, green",
			HairColors:      "none",
			EyeColors:       "red, pink",
			Language:        "Neimoidia",
			HomeworldURL:    "https://swapi.dev/api/planets/18/",
		},
	}

	for _, sp := range species {
		DB.Create(&sp)
	}

	// Create starships - expanded list
	starships := []models.Starship{
		{
			URL:                  "https://swapi.dev/api/starships/1/",
			Name:                 "Death Star",
			Model:                "DS-1 Orbital Battle Station",
			Manufacturer:         "Imperial Department of Military Research, Sienar Fleet Systems",
			CostInCredits:        "1000000000000",
			Length:               "120000",
			MaxAtmospheringSpeed: "n/a",
			Crew:                 "342,953",
			Passengers:           "843,342",
			CargoCapacity:        "1000000000000",
			Consumables:          "3 years",
			HyperdriveRating:     "4.0",
			MGLT:                 "10",
			StarshipClass:        "Deep Space Mobile Battlestation",
		},
		{
			URL:                  "https://swapi.dev/api/starships/2/",
			Name:                 "CR90 corvette",
			Model:                "CR90 corvette",
			Manufacturer:         "Corellian Engineering Corporation",
			CostInCredits:        "3500000",
			Length:               "150",
			MaxAtmospheringSpeed: "950",
			Crew:                 "30-165",
			Passengers:           "600",
			CargoCapacity:        "3000000",
			Consumables:          "1 year",
			HyperdriveRating:     "2.0",
			MGLT:                 "60",
			StarshipClass:        "corvette",
		},
		{
			URL:                  "https://swapi.dev/api/starships/3/",
			Name:                 "Star Destroyer",
			Model:                "Imperial I-class Star Destroyer",
			Manufacturer:         "Kuat Drive Yards",
			CostInCredits:        "150000000",
			Length:               "1,600",
			MaxAtmospheringSpeed: "975",
			Crew:                 "47,060",
			Passengers:           "n/a",
			CargoCapacity:        "36000000",
			Consumables:          "2 years",
			HyperdriveRating:     "2.0",
			MGLT:                 "60",
			StarshipClass:        "Star Destroyer",
		},
		{
			URL:                  "https://swapi.dev/api/starships/4/",
			Name:                 "Millennium Falcon",
			Model:                "YT-1300 light freighter",
			Manufacturer:         "Corellian Engineering Corporation",
			CostInCredits:        "100000",
			Length:               "34.37",
			MaxAtmospheringSpeed: "1050",
			Crew:                 "4",
			Passengers:           "6",
			CargoCapacity:        "100000",
			Consumables:          "2 months",
			HyperdriveRating:     "0.5",
			MGLT:                 "75",
			StarshipClass:        "Light freighter",
		},
		{
			URL:                  "https://swapi.dev/api/starships/5/",
			Name:                 "X-wing",
			Model:                "T-65 X-wing",
			Manufacturer:         "Incom Corporation",
			CostInCredits:        "149999",
			Length:               "12.5",
			MaxAtmospheringSpeed: "1050",
			Crew:                 "1",
			Passengers:           "0",
			CargoCapacity:        "110",
			Consumables:          "1 week",
			HyperdriveRating:     "1.0",
			MGLT:                 "100",
			StarshipClass:        "Starfighter",
		},
		{
			URL:                  "https://swapi.dev/api/starships/6/",
			Name:                 "TIE Advanced x1",
			Model:                "Twin Ion Engine Advanced x1",
			Manufacturer:         "Sienar Fleet Systems",
			CostInCredits:        "unknown",
			Length:               "9.2",
			MaxAtmospheringSpeed: "1200",
			Crew:                 "1",
			Passengers:           "0",
			CargoCapacity:        "150",
			Consumables:          "5 days",
			HyperdriveRating:     "1.0",
			MGLT:                 "105",
			StarshipClass:        "Starfighter",
		},
		{
			URL:                  "https://swapi.dev/api/starships/7/",
			Name:                 "Slave I",
			Model:                "Firespray-31-class patrol and attack",
			Manufacturer:         "Kuat Systems Engineering",
			CostInCredits:        "unknown",
			Length:               "21.5",
			MaxAtmospheringSpeed: "1000",
			Crew:                 "1",
			Passengers:           "6",
			CargoCapacity:        "70000",
			Consumables:          "1 month",
			HyperdriveRating:     "3.0",
			MGLT:                 "70",
			StarshipClass:        "Patrol craft",
		},
		{
			URL:                  "https://swapi.dev/api/starships/8/",
			Name:                 "Y-wing",
			Model:                "BTL Y-wing",
			Manufacturer:         "Koensayr Manufacturing",
			CostInCredits:        "134999",
			Length:               "14",
			MaxAtmospheringSpeed: "1000",
			Crew:                 "2",
			Passengers:           "0",
			CargoCapacity:        "110",
			Consumables:          "1 week",
			HyperdriveRating:     "1.0",
			MGLT:                 "80",
			StarshipClass:        "assault starfighter",
		},
		{
			URL:                  "https://swapi.dev/api/starships/9/",
			Name:                 "TIE Fighter",
			Model:                "Twin Ion Engine/Ln Starfighter",
			Manufacturer:         "Sienar Fleet Systems",
			CostInCredits:        "unknown",
			Length:               "6.4",
			MaxAtmospheringSpeed: "1200",
			Crew:                 "1",
			Passengers:           "0",
			CargoCapacity:        "65",
			Consumables:          "2 days",
			HyperdriveRating:     "0",
			MGLT:                 "100",
			StarshipClass:        "Starfighter",
		},
		{
			URL:                  "https://swapi.dev/api/starships/10/",
			Name:                 "A-wing",
			Model:                "RZ-1 A-wing Interceptor",
			Manufacturer:         "Alliance Underground Engineering, Incom Corporation",
			CostInCredits:        "175000",
			Length:               "9.6",
			MaxAtmospheringSpeed: "1300",
			Crew:                 "1",
			Passengers:           "0",
			CargoCapacity:        "40",
			Consumables:          "1 week",
			HyperdriveRating:     "1.0",
			MGLT:                 "120",
			StarshipClass:        "Starfighter",
		},
	}

	for _, starship := range starships {
		DB.Create(&starship)
	}

	// Create characters - expanded list from all eras
	characters := []models.Character{
		// Original Trilogy Heroes
		{
			URL:       "https://swapi.dev/api/people/1/",
			Name:      "Luke Skywalker",
			BirthYear: "19BBY",
			EyeColor:  "blue",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/1/",
			HairColor: "blond",
			Height:    "172",
			Mass:      "77",
		},
		{
			URL:       "https://swapi.dev/api/people/2/",
			Name:      "Leia Organa",
			BirthYear: "19BBY",
			EyeColor:  "brown",
			Gender:    "female",
			Homeworld: "https://swapi.dev/api/planets/2/",
			HairColor: "brown",
			Height:    "150",
			Mass:      "49",
		},
		{
			URL:       "https://swapi.dev/api/people/3/",
			Name:      "Han Solo",
			BirthYear: "29BBY",
			EyeColor:  "brown",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/22/",
			HairColor: "brown",
			Height:    "180",
			Mass:      "80",
		},
		{
			URL:       "https://swapi.dev/api/people/4/",
			Name:      "Chewbacca",
			BirthYear: "200BBY",
			EyeColor:  "blue",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/14/",
			HairColor: "brown",
			Height:    "228",
			Mass:      "112",
		},
		// Droids
		{
			URL:       "https://swapi.dev/api/people/5/",
			Name:      "C-3PO",
			BirthYear: "112BBY",
			EyeColor:  "yellow",
			Gender:    "n/a",
			Homeworld: "https://swapi.dev/api/planets/1/",
			HairColor: "n/a",
			Height:    "167",
			Mass:      "75",
		},
		{
			URL:       "https://swapi.dev/api/people/6/",
			Name:      "R2-D2",
			BirthYear: "33BBY",
			EyeColor:  "red",
			Gender:    "n/a",
			Homeworld: "https://swapi.dev/api/planets/8/",
			HairColor: "n/a",
			Height:    "96",
			Mass:      "32",
		},
		// Sith and Empire
		{
			URL:       "https://swapi.dev/api/people/7/",
			Name:      "Darth Vader",
			BirthYear: "41.9BBY",
			EyeColor:  "yellow",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/1/",
			HairColor: "none",
			Height:    "202",
			Mass:      "136",
		},
		{
			URL:       "https://swapi.dev/api/people/8/",
			Name:      "Emperor Palpatine",
			BirthYear: "82BBY",
			EyeColor:  "yellow",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/8/",
			HairColor: "grey",
			Height:    "170",
			Mass:      "75",
		},
		// Jedi Masters
		{
			URL:       "https://swapi.dev/api/people/9/",
			Name:      "Obi-Wan Kenobi",
			BirthYear: "57BBY",
			EyeColor:  "blue-gray",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/20/",
			HairColor: "auburn, white",
			Height:    "182",
			Mass:      "77",
		},
		{
			URL:       "https://swapi.dev/api/people/10/",
			Name:      "Yoda",
			BirthYear: "896BBY",
			EyeColor:  "brown",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/28/",
			HairColor: "white",
			Height:    "66",
			Mass:      "17",
		},
		// Prequel Era
		{
			URL:       "https://swapi.dev/api/people/11/",
			Name:      "Anakin Skywalker",
			BirthYear: "41.9BBY",
			EyeColor:  "blue",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/1/",
			HairColor: "blond",
			Height:    "188",
			Mass:      "84",
		},
		{
			URL:       "https://swapi.dev/api/people/12/",
			Name:      "Padmé Amidala",
			BirthYear: "46BBY",
			EyeColor:  "brown",
			Gender:    "female",
			Homeworld: "https://swapi.dev/api/planets/8/",
			HairColor: "brown",
			Height:    "165",
			Mass:      "45",
		},
		{
			URL:       "https://swapi.dev/api/people/13/",
			Name:      "Mace Windu",
			BirthYear: "72BBY",
			EyeColor:  "brown",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/42/",
			HairColor: "none",
			Height:    "188",
			Mass:      "84",
		},
		{
			URL:       "https://swapi.dev/api/people/14/",
			Name:      "Qui-Gon Jinn",
			BirthYear: "92BBY",
			EyeColor:  "blue",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/44/",
			HairColor: "brown",
			Height:    "193",
			Mass:      "89",
		},
		{
			URL:       "https://swapi.dev/api/people/15/",
			Name:      "Jar Jar Binks",
			BirthYear: "52BBY",
			EyeColor:  "orange",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/8/",
			HairColor: "none",
			Height:    "196",
			Mass:      "66",
		},
		// Sequel Trilogy
		{
			URL:       "https://swapi.dev/api/people/16/",
			Name:      "Rey",
			BirthYear: "15ABY",
			EyeColor:  "hazel",
			Gender:    "female",
			Homeworld: "https://swapi.dev/api/planets/43/",
			HairColor: "brown",
			Height:    "170",
			Mass:      "54",
		},
		{
			URL:       "https://swapi.dev/api/people/17/",
			Name:      "Finn",
			BirthYear: "11ABY",
			EyeColor:  "dark",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/28/",
			HairColor: "black",
			Height:    "178",
			Mass:      "73",
		},
		{
			URL:       "https://swapi.dev/api/people/18/",
			Name:      "Poe Dameron",
			BirthYear: "2ABY",
			EyeColor:  "brown",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/45/",
			HairColor: "brown",
			Height:    "172",
			Mass:      "80",
		},
		{
			URL:       "https://swapi.dev/api/people/19/",
			Name:      "Kylo Ren",
			BirthYear: "5ABY",
			EyeColor:  "brown",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/28/",
			HairColor: "black",
			Height:    "189",
			Mass:      "89",
		},
		// Bounty Hunters and Rogues
		{
			URL:       "https://swapi.dev/api/people/20/",
			Name:      "Boba Fett",
			BirthYear: "31.5BBY",
			EyeColor:  "brown",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/10/",
			HairColor: "black",
			Height:    "183",
			Mass:      "78.2",
		},
		{
			URL:       "https://swapi.dev/api/people/21/",
			Name:      "Jango Fett",
			BirthYear: "66BBY",
			EyeColor:  "brown",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/53/",
			HairColor: "black",
			Height:    "183",
			Mass:      "79",
		},
		{
			URL:       "https://swapi.dev/api/people/22/",
			Name:      "Lando Calrissian",
			BirthYear: "31BBY",
			EyeColor:  "brown",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/30/",
			HairColor: "black",
			Height:    "177",
			Mass:      "79",
		},
		// Villains and Sith
		{
			URL:       "https://swapi.dev/api/people/23/",
			Name:      "Count Dooku",
			BirthYear: "102BBY",
			EyeColor:  "brown",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/52/",
			HairColor: "white",
			Height:    "193",
			Mass:      "80",
		},
		{
			URL:       "https://swapi.dev/api/people/24/",
			Name:      "Darth Maul",
			BirthYear: "54BBY",
			EyeColor:  "yellow",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/36/",
			HairColor: "none",
			Height:    "175",
			Mass:      "80",
		},
		{
			URL:       "https://swapi.dev/api/people/25/",
			Name:      "General Grievous",
			BirthYear: "unknown",
			EyeColor:  "green, yellow",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/50/",
			HairColor: "none",
			Height:    "216",
			Mass:      "159",
		},
		// Supporting Characters
		{
			URL:       "https://swapi.dev/api/people/26/",
			Name:      "Owen Lars",
			BirthYear: "52BBY",
			EyeColor:  "blue",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/1/",
			HairColor: "brown, grey",
			Height:    "178",
			Mass:      "120",
		},
		{
			URL:       "https://swapi.dev/api/people/27/",
			Name:      "Beru Whitesun Lars",
			BirthYear: "47BBY",
			EyeColor:  "blue",
			Gender:    "female",
			Homeworld: "https://swapi.dev/api/planets/1/",
			HairColor: "brown",
			Height:    "165",
			Mass:      "75",
		},
		{
			URL:       "https://swapi.dev/api/people/28/",
			Name:      "Mon Mothma",
			BirthYear: "48BBY",
			EyeColor:  "blue",
			Gender:    "female",
			Homeworld: "https://swapi.dev/api/planets/32/",
			HairColor: "auburn",
			Height:    "150",
			Mass:      "unknown",
		},
		{
			URL:       "https://swapi.dev/api/people/29/",
			Name:      "Admiral Ackbar",
			BirthYear: "unknown",
			EyeColor:  "orange",
			Gender:    "male",
			Homeworld: "https://swapi.dev/api/planets/31/",
			HairColor: "none",
			Height:    "180",
			Mass:      "83",
		},
		{
			URL:       "https://swapi.dev/api/people/30/",
			Name:      "Jabba the Hutt",
			BirthYear: "600BBY",
			EyeColor:  "orange",
			Gender:    "hermaphrodite",
			Homeworld: "https://swapi.dev/api/planets/24/",
			HairColor: "n/a",
			Height:    "175",
			Mass:      "1,358",
		},
	}

	for _, character := range characters {
		DB.Create(&character)
	}

	// Create organizations
	organizations := []models.Organization{
		{
			URL:         "https://swapi.dev/api/organizations/1/",
			Name:        "Jedi Order",
			Type:        "religious",
			Description: "An ancient monastic peacekeeping organization unified by its belief and observance of the Force.",
			Founded:     "25,000 BBY",
			Dissolved:   "19 BBY",
			Homeworld:   "https://swapi.dev/api/planets/9/",
			Leader:      "Jedi High Council",
		},
		{
			URL:         "https://swapi.dev/api/organizations/2/",
			Name:        "Galactic Empire",
			Type:        "government",
			Description: "The authoritarian galactic government that replaced the Galactic Republic.",
			Founded:     "19 BBY",
			Dissolved:   "5 ABY",
			Homeworld:   "https://swapi.dev/api/planets/9/",
			Leader:      "Emperor Palpatine",
		},
		{
			URL:         "https://swapi.dev/api/organizations/3/",
			Name:        "Rebel Alliance",
			Type:        "military",
			Description: "A resistance movement formed to oppose the rule of the Galactic Empire.",
			Founded:     "2 BBY",
			Dissolved:   "4 ABY",
			Homeworld:   "https://swapi.dev/api/planets/3/",
			Leader:      "Mon Mothma",
		},
		{
			URL:         "https://swapi.dev/api/organizations/4/",
			Name:        "Sith Order",
			Type:        "religious",
			Description: "An ancient order of Force-wielders devoted to the dark side of the Force.",
			Founded:     "6,900 BBY",
			Dissolved:   "",
			Homeworld:   "https://swapi.dev/api/planets/44/",
			Leader:      "Darth Sidious",
		},
		{
			URL:         "https://swapi.dev/api/organizations/5/",
			Name:        "First Order",
			Type:        "military",
			Description: "A military junta that emerged from the Unknown Regions after the fall of the Empire.",
			Founded:     "5 ABY",
			Dissolved:   "",
			Homeworld:   "https://swapi.dev/api/planets/51/",
			Leader:      "Supreme Leader Snoke",
		},
	}

	for _, org := range organizations {
		DB.Create(&org)
	}

	// Create weapons
	weapons := []models.Weapon{
		{
			URL:          "https://swapi.dev/api/weapons/1/",
			Name:         "Luke's Lightsaber",
			Type:         "lightsaber",
			Manufacturer: "Luke Skywalker",
			Model:        "Jedi lightsaber",
			Description:  "A blue-bladed lightsaber constructed by Luke Skywalker.",
			Length:       "28 cm",
			Weight:       "1 kg",
			Color:        "blue",
			CrystalType:  "synthetic crystal",
		},
		{
			URL:          "https://swapi.dev/api/weapons/2/",
			Name:         "Darth Vader's Lightsaber",
			Type:         "lightsaber",
			Manufacturer: "Darth Vader",
			Model:        "Sith lightsaber",
			Description:  "A red-bladed lightsaber wielded by Darth Vader.",
			Length:       "28 cm",
			Weight:       "1 kg",
			Color:        "red",
			CrystalType:  "synthetic crystal",
		},
		{
			URL:          "https://swapi.dev/api/weapons/3/",
			Name:         "Obi-Wan's Lightsaber",
			Type:         "lightsaber",
			Manufacturer: "Obi-Wan Kenobi",
			Model:        "Jedi lightsaber",
			Description:  "A blue-bladed lightsaber constructed by Obi-Wan Kenobi.",
			Length:       "28 cm",
			Weight:       "1 kg",
			Color:        "blue",
			CrystalType:  "Ilum crystal",
		},
		{
			URL:          "https://swapi.dev/api/weapons/4/",
			Name:         "Yoda's Lightsaber",
			Type:         "lightsaber",
			Manufacturer: "Yoda",
			Model:        "Jedi lightsaber",
			Description:  "A green-bladed lightsaber with a shorter hilt for Yoda's size.",
			Length:       "20 cm",
			Weight:       "0.5 kg",
			Color:        "green",
			CrystalType:  "Adegan crystal",
		},
		{
			URL:          "https://swapi.dev/api/weapons/5/",
			Name:         "Death Star Superlaser",
			Type:         "superweapon",
			Manufacturer: "Imperial Department of Military Research",
			Model:        "Superlaser",
			Description:  "A planet-destroying superlaser mounted on the Death Star.",
			Length:       "unknown",
			Weight:       "unknown",
			Color:        "green",
			CrystalType:  "kyber crystals",
		},
	}

	for _, weapon := range weapons {
		DB.Create(&weapon)
	}

	// Create planets
	planets := []models.Planet{
		{
			URL:            "https://swapi.dev/api/planets/1/",
			Name:           "Tatooine",
			RotationPeriod: "23",
			OrbitalPeriod:  "304",
			Diameter:       "10465",
			Climate:        "arid",
			Gravity:        "1 standard",
			Terrain:        "desert",
			SurfaceWater:   "1",
			Population:     "200000",
		},
		{
			URL:            "https://swapi.dev/api/planets/2/",
			Name:           "Alderaan",
			RotationPeriod: "24",
			OrbitalPeriod:  "364",
			Diameter:       "12500",
			Climate:        "temperate",
			Gravity:        "1 standard",
			Terrain:        "grasslands, mountains",
			SurfaceWater:   "40",
			Population:     "2000000000",
		},
		{
			URL:            "https://swapi.dev/api/planets/3/",
			Name:           "Yavin IV",
			RotationPeriod: "24",
			OrbitalPeriod:  "4818",
			Diameter:       "10200",
			Climate:        "temperate, tropical",
			Gravity:        "1 standard",
			Terrain:        "jungle, rainforests",
			SurfaceWater:   "8",
			Population:     "1000",
		},
		{
			URL:            "https://swapi.dev/api/planets/4/",
			Name:           "Hoth",
			RotationPeriod: "23",
			OrbitalPeriod:  "549",
			Diameter:       "7200",
			Climate:        "frozen",
			Gravity:        "1.1 standard",
			Terrain:        "tundra, ice caves, mountain ranges",
			SurfaceWater:   "100",
			Population:     "unknown",
		},
		{
			URL:            "https://swapi.dev/api/planets/5/",
			Name:           "Dagobah",
			RotationPeriod: "23",
			OrbitalPeriod:  "341",
			Diameter:       "8900",
			Climate:        "murky",
			Gravity:        "N/A",
			Terrain:        "swamp, jungles",
			SurfaceWater:   "8",
			Population:     "unknown",
		},
		{
			URL:            "https://swapi.dev/api/planets/6/",
			Name:           "Bespin",
			RotationPeriod: "12",
			OrbitalPeriod:  "5110",
			Diameter:       "118000",
			Climate:        "temperate",
			Gravity:        "1.5 standard",
			Terrain:        "gas giant",
			SurfaceWater:   "0",
			Population:     "6000000",
		},
		{
			URL:            "https://swapi.dev/api/planets/7/",
			Name:           "Endor",
			RotationPeriod: "18",
			OrbitalPeriod:  "402",
			Diameter:       "4900",
			Climate:        "temperate",
			Gravity:        "0.85 standard",
			Terrain:        "forests, mountains, lakes",
			SurfaceWater:   "8",
			Population:     "30000000",
		},
		{
			URL:            "https://swapi.dev/api/planets/8/",
			Name:           "Naboo",
			RotationPeriod: "26",
			OrbitalPeriod:  "312",
			Diameter:       "12120",
			Climate:        "temperate",
			Gravity:        "1 standard",
			Terrain:        "grassy hills, swamps, forests, mountains",
			SurfaceWater:   "12",
			Population:     "4500000000",
		},
		{
			URL:            "https://swapi.dev/api/planets/9/",
			Name:           "Coruscant",
			RotationPeriod: "24",
			OrbitalPeriod:  "368",
			Diameter:       "12240",
			Climate:        "temperate",
			Gravity:        "1 standard",
			Terrain:        "cityscape, mountains",
			SurfaceWater:   "unknown",
			Population:     "1000000000000",
		},
		{
			URL:            "https://swapi.dev/api/planets/10/",
			Name:           "Kamino",
			RotationPeriod: "27",
			OrbitalPeriod:  "463",
			Diameter:       "19720",
			Climate:        "temperate",
			Gravity:        "1 standard",
			Terrain:        "ocean",
			SurfaceWater:   "100",
			Population:     "1000000000",
		},
	}

	for _, planet := range planets {
		DB.Create(&planet)
	}

	log.Println("Database seeded successfully")

	// Seed quiz questions
	SeedQuizQuestions()
}
